copy adelie doc build/deploy steps

diff --git a/.github/workflows/sphinx.yml b/.github/workflows/sphinx.yml
--- a/.github/workflows/sphinx.yml
+++ b/.github/workflows/sphinx.yml
@@ -1,38 +1,46 @@
+# adapted from: https://github.com/JamesYang007/adelie/blob/main/.github/workflows/test_docs.yml#L37
 name: "Sphinx: Render docs"
 
 on: push
 
 jobs:
   build:
+    name: Document 📄
     runs-on: ubuntu-latest
     permissions:
-      contents: write
+      contents: write   # IMPORTANT: mandatory for pushing to gh-pages 
+
     steps:
     - uses: actions/checkout@v4
-      with:
-        persist-credentials: false
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: "3.x"
-    - name: Install pandoc
+    - uses: actions/setup-python@v3
+    - name: Install dependencies
       run: |
         sudo wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-amd64.deb -O /tmp/pandoc-3.1.8-1-amd64.deb
         sudo dpkg -i /tmp/pandoc-3.1.8-1-amd64.deb
-    - name: Build HTML
-      run: |
         python -m pip install --upgrade pip
         pip install sphinx sphinx_design numpydoc pandoc nbsphinx pydata_sphinx_theme
         pip install sweepystats
+    - name: Build documentation
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git fetch --all
+        git checkout gh-pages
+        git merge master -Xtheirs --allow-unrelated-histories # keeps main changes over gh-pages
+        cd docs
+        rm -rf _images _sources _static .doctrees generated notebooks *.html *.inv *.js .buildinfo
+        cd ..
         sphinx-build -b html docs/ docs/_build/html
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
+        cp -r docs/_build/html/* docs
+        touch docs/.nojekyll
+    - name: Commit documentation changes
+      run: |
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
       with:
-        name: html-docs
-        path: docs/_build/html/
-    - name: Deploy
-      uses: peaceiris/actions-gh-pages@v3
-      if: github.ref == 'refs/heads/main'
-      with:
+        branch: gh-pages
+        directory: docs
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: docs/_build/html
